#!/usr/bin/env bash
set -euo pipefail

# Telvy — Automated VPS Setup
# Usage: sudo bash setup.sh --domain example.com --email admin@example.com

# --- Parse arguments ---

DOMAIN=""
EMAIL=""
PORT=9000
SKIP_TLS=false
TURN_SECRET=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --domain)     DOMAIN="$2"; shift 2 ;;
    --email)      EMAIL="$2"; shift 2 ;;
    --port)       PORT="$2"; shift 2 ;;
    --skip-tls)   SKIP_TLS=true; shift ;;
    --turn-secret) TURN_SECRET="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [[ -z "$DOMAIN" || -z "$EMAIL" ]]; then
  echo "Usage: sudo bash setup.sh --domain example.com --email admin@example.com"
  echo ""
  echo "Options:"
  echo "  --domain       Domain name (required)"
  echo "  --email        Email for Let's Encrypt (required)"
  echo "  --port         Signaling server port (default: 9000)"
  echo "  --skip-tls     Skip Let's Encrypt certificate setup"
  echo "  --turn-secret  Custom TURN secret (default: auto-generated)"
  exit 1
fi

if [[ $EUID -ne 0 ]]; then
  echo "Error: This script must be run as root (sudo)"
  exit 1
fi

# --- Configuration ---

EXTERNAL_IP=$(curl -4 -s --max-time 5 ifconfig.me || curl -4 -s --max-time 5 icanhazip.com)
TURN_SECRET="${TURN_SECRET:-$(openssl rand -hex 32)}"
APP_DIR="/opt/telvy"
WEB_DIR="/var/www/telvy"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$(dirname "$SCRIPT_DIR")"

echo "================================================"
echo "  Telvy — VPS Setup"
echo "================================================"
echo "  Domain:      $DOMAIN"
echo "  Email:       $EMAIL"
echo "  External IP: $EXTERNAL_IP"
echo "  Port:        $PORT"
echo "  TLS:         $(if $SKIP_TLS; then echo 'skipped'; else echo 'Let'\''s Encrypt'; fi)"
echo "================================================"
echo ""

# --- Install packages ---

echo "[1/10] Installing packages..."
apt-get update -qq
apt-get install -y -qq nginx coturn certbot curl unzip > /dev/null 2>&1
echo "  Done."

# --- Install Bun ---

echo "[2/10] Installing Bun..."
if ! command -v bun &> /dev/null; then
  curl -fsSL https://bun.sh/install | bash > /dev/null 2>&1
  export BUN_INSTALL="$HOME/.bun"
  export PATH="$BUN_INSTALL/bin:$PATH"
fi
echo "  Bun $(bun --version)"

# --- TLS certificates ---

echo "[3/10] Setting up TLS..."
if $SKIP_TLS; then
  echo "  Skipped."
else
  if [[ ! -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]]; then
    systemctl stop nginx 2>/dev/null || true
    certbot certonly --standalone --non-interactive --agree-tos \
      --email "$EMAIL" -d "$DOMAIN"
    systemctl start nginx 2>/dev/null || true
    echo "  Certificate obtained."
  else
    echo "  Certificate already exists."
  fi
fi

# --- Deploy static files ---

echo "[4/10] Deploying static files..."
mkdir -p "$WEB_DIR"
if [[ -d "$SOURCE_DIR/dist" ]]; then
  cp -r "$SOURCE_DIR/dist/"* "$WEB_DIR/"
  echo "  Copied dist/ to $WEB_DIR"
else
  echo "  Warning: dist/ not found. Run 'bun run build' first."
fi

# --- Deploy server ---

echo "[5/10] Deploying signaling server..."
mkdir -p "$APP_DIR/server"
cp "$SOURCE_DIR/server/index.ts" "$APP_DIR/server/"
cp "$SOURCE_DIR/package.json" "$APP_DIR/"

# Create .env
cat > "$APP_DIR/.env" <<ENVEOF
TURN_SECRET=$TURN_SECRET
TURN_DOMAIN=$DOMAIN
PEER_PORT=$PORT
ENVEOF
chmod 600 "$APP_DIR/.env"

# Install production dependencies
cd "$APP_DIR"
bun install --production > /dev/null 2>&1
echo "  Done."

# --- Configure coturn ---

echo "[6/10] Configuring coturn..."
mkdir -p /etc/coturn
cat > /etc/coturn/telvy.conf <<COTURNEOF
# Telvy coturn configuration — generated by setup.sh

listening-port=3478
tls-listening-port=5349

realm=$DOMAIN
server-name=$DOMAIN
external-ip=$EXTERNAL_IP

$(if ! $SKIP_TLS; then
cat <<TLSEOF
cert=/etc/letsencrypt/live/$DOMAIN/fullchain.pem
pkey=/etc/letsencrypt/live/$DOMAIN/privkey.pem
TLSEOF
fi)

use-auth-secret
static-auth-secret=$TURN_SECRET

no-multicast-peers
no-cli
stale-nonce=300
fingerprint

denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=240.0.0.0-255.255.255.255

no-stdout-log
no-syslog
COTURNEOF

# Enable coturn daemon
sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn 2>/dev/null || true
echo "TURNSERVER_ENABLED=1" >> /etc/default/coturn 2>/dev/null || true

# Point coturn to our config
if [[ -f /etc/systemd/system/coturn.service.d/override.conf ]]; then
  rm /etc/systemd/system/coturn.service.d/override.conf
fi
mkdir -p /etc/systemd/system/coturn.service.d
cat > /etc/systemd/system/coturn.service.d/override.conf <<SVCEOF
[Service]
ExecStart=
ExecStart=/usr/bin/turnserver -c /etc/coturn/telvy.conf
SVCEOF
echo "  Done."

# --- Configure nginx ---

echo "[7/10] Configuring nginx..."

if $SKIP_TLS; then
  # HTTP only (testing)
  cat > /etc/nginx/sites-available/telvy <<NGINXEOF
server {
    listen 80;
    server_name $DOMAIN;

    root $WEB_DIR;
    index index.html;

    # Security headers
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://$DOMAIN ws://$DOMAIN; media-src 'self'" always;

    location /ws {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 86400;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
NGINXEOF
else
  # HTTPS with TLS
  cat > /etc/nginx/sites-available/telvy <<NGINXEOF
server {
    listen 80;
    server_name $DOMAIN;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    # TLS hardening
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_stapling on;
    ssl_stapling_verify on;

    # Security headers
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://$DOMAIN; media-src 'self'" always;

    root $WEB_DIR;
    index index.html;

    location /ws {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 86400;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
NGINXEOF
fi

ln -sf /etc/nginx/sites-available/telvy /etc/nginx/sites-enabled/telvy
rm -f /etc/nginx/sites-enabled/default
nginx -t
echo "  Done."

# --- Systemd service ---

echo "[8/10] Creating systemd service..."
# Copy bun to system path so www-data can access it (root's home is not traversable)
cp "$(which bun)" /usr/local/bin/bun 2>/dev/null || true
chmod 755 /usr/local/bin/bun
BUN_PATH=/usr/local/bin/bun

cat > /etc/systemd/system/telvy-signaling.service <<SVCEOF
[Unit]
Description=Telvy Signaling Server
After=network.target

[Service]
Type=simple
User=www-data
WorkingDirectory=$APP_DIR
EnvironmentFile=$APP_DIR/.env
ExecStart=$BUN_PATH run server/index.ts
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
SVCEOF

chown -R www-data:www-data "$APP_DIR"
systemctl daemon-reload
echo "  Done."

# --- Firewall ---

echo "[9/10] Configuring firewall..."
ufw --force reset > /dev/null 2>&1
ufw default deny incoming > /dev/null 2>&1
ufw default allow outgoing > /dev/null 2>&1
ufw allow 22/tcp > /dev/null 2>&1    # SSH
ufw allow 443/tcp > /dev/null 2>&1   # HTTPS
ufw allow 3478/tcp > /dev/null 2>&1  # TURN TCP
ufw allow 3478/udp > /dev/null 2>&1  # TURN UDP
ufw allow 5349/tcp > /dev/null 2>&1  # TURNS
if ! $SKIP_TLS; then
  ufw allow 80/tcp > /dev/null 2>&1  # HTTP redirect + certbot renewal
fi
ufw --force enable > /dev/null 2>&1
echo "  Done."

# --- Start services ---

echo "[10/10] Starting services..."
systemctl enable --now coturn
systemctl enable --now telvy-signaling
systemctl reload nginx
echo "  Done."

# --- Summary ---

echo ""
echo "================================================"
echo "  Telvy is running!"
echo "================================================"
PROTO="https"
$SKIP_TLS && PROTO="http"
echo "  URL:         $PROTO://$DOMAIN"
echo "  Signaling:   $PROTO://$DOMAIN/ws"
echo "  TURN:        $DOMAIN:3478 (UDP/TCP)"
echo "  TURNS:       $DOMAIN:5349 (TLS)"
echo ""
echo "  TURN_SECRET stored in $APP_DIR/.env"
echo ""
echo "  Verify:"
echo "    curl -s $PROTO://$DOMAIN/api/turn-credentials | head -c 80"
echo "    systemctl status telvy-signaling"
echo "    systemctl status coturn"
echo "================================================"
